Spotify is a digital music service that gives you access to millions of songs.Artists upload their songs or albums and people get access to their music through the app. Songs and artists with the most streams generate royalties or investments in exclusive content. Spotify identifies songs with the most streams and also predicts which songs are likely to be hits based on the artists popularity or time of release.It also understands how listener preferences change over time. This dataset contains the most popular songs in 2023. It shows the spotify stream count,the release dates,the track name and the artist name. From this dataset, we want to get the most popular artist,most popular songs,average streams per year,songs with the highest stream counts and which top artists who consistently produces hits and from make a conclusion

To be able to run the data we obtained about Spotify,we need to first import the necessary tools to run the data.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import csv

Then load the Dataset

In [2]:
file_path=r"C:\Users\User\Documents\Phase1_Project\Popular_Spotify_Songs.csv"
with open(file_path, encoding="latin1") as file:
    reader = csv.DictReader(file)
    for row in reader:
        row

In [3]:
df=pd.read_csv(r"C:\Users\User\Documents\Phase1_Project\Popular_Spotify_Songs.csv",encoding="latin1")
df.head(10)

track_name              artist(s)_name  \
0  Seven (feat. Latto) (Explicit Ver.)            Latto, Jung Kook   
1                                 LALA                 Myke Towers   
2                              vampire              Olivia Rodrigo   
3                         Cruel Summer                Taylor Swift   
4                       WHERE SHE GOES                   Bad Bunny   
5                             Sprinter           Dave, Central Cee   
6                      Ella Baila Sola  Eslabon Armado, Peso Pluma   
7                             Columbia                     Quevedo   
8                             fukumean                       Gunna   
9                      La Bebe - Remix       Peso Pluma, Yng Lvcas   

   artist_count  released_year  released_month  released_day  \
0             2           2023               7            14   
1             1           2023               3            23   
2             1           2023               6            30   
3             1           2019               8            23   
4             1           2023               5            18   
5             2           2023               6             1   
6             2           2023               3            16   
7             1           2023               7             7   
8             1           2023               5            15   
9             2           2023               3            17   

   in_spotify_playlists  in_spotify_charts    streams  in_apple_playlists  \
0                   553                147  141381703                  43   
1                  1474                 48  133716286                  48   
2                  1397                113  140003974                  94   
3                  7858                100  800840817                 116   
4                  3133                 50  303236322                  84   
5                  2186                 91  183706234                  67   
6                  3090                 50  725980112                  34   
7                   714                 43   58149378                  25   
8                  1096                 83   95217315                  60   
9                  2953                 44  553634067                  49   

   ...  bpm key   mode danceability_%  valence_% energy_% acousticness_%  \
0  ...  125   B  Major             80         89       83             31   
1  ...   92  C#  Major             71         61       74              7   
2  ...  138   F  Major             51         32       53             17   
3  ...  170   A  Major             55         58       72             11   
4  ...  144   A  Minor             65         23       80             14   
5  ...  141  C#  Major             92         66       58             19   
6  ...  148   F  Minor             67         83       76             48   
7  ...  100   F  Major             67         26       71             37   
8  ...  130  C#  Minor             85         22       62             12   
9  ...  170   D  Minor             81         56       48             21   

   instrumentalness_%  liveness_%  speechiness_%  
0                   0           8              4  
1                   0          10              4  
2                   0          31              6  
3                   0          11             15  
4                  63          11              6  
5                   0           8             24  
6                   0           8              3  
7                   0          11              4  
8                   0          28              9  
9                   0           8             33  

[10 rows x 24 columns]

We need a summary of our data.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64 
 3   released_year         953 non-null    int64 
 4   released_month        953 non-null    int64 
 5   released_day          953 non-null    int64 
 6   in_spotify_playlists  953 non-null    int64 
 7   in_spotify_charts     953 non-null    int64 
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64 
 10  in_apple_charts       953 non-null    int64 
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64 
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64 
 15  key                   858 non-null    ob

From the data we have 953 rows representing artist names and track names and 24 columns

In [5]:
df.describe()

artist_count  released_year  released_month  released_day  \
count    953.000000     953.000000      953.000000    953.000000   
mean       1.556139    2018.238195        6.033578     13.930745   
std        0.893044      11.116218        3.566435      9.201949   
min        1.000000    1930.000000        1.000000      1.000000   
25%        1.000000    2020.000000        3.000000      6.000000   
50%        1.000000    2022.000000        6.000000     13.000000   
75%        2.000000    2022.000000        9.000000     22.000000   
max        8.000000    2023.000000       12.000000     31.000000   

       in_spotify_playlists  in_spotify_charts  in_apple_playlists  \
count            953.000000         953.000000          953.000000   
mean            5200.124869          12.009444           67.812172   
std             7897.608990          19.575992           86.441493   
min               31.000000           0.000000            0.000000   
25%              875.000000           0.000000           13.000000   
50%             2224.000000           3.000000           34.000000   
75%             5542.000000          16.000000           88.000000   
max            52898.000000         147.000000          672.000000   

       in_apple_charts  in_deezer_charts         bpm  danceability_%  \
count       953.000000        953.000000  953.000000       953.00000   
mean         51.908709          2.666317  122.540399        66.96957   
std          50.630241          6.035599   28.057802        14.63061   
min           0.000000          0.000000   65.000000        23.00000   
25%           7.000000          0.000000  100.000000        57.00000   
50%          38.000000          0.000000  121.000000        69.00000   
75%          87.000000          2.000000  140.000000        78.00000   
max         275.000000         58.000000  206.000000        96.00000   

        valence_%    energy_%  acousticness_%  instrumentalness_%  liveness_%  \
count  953.000000  953.000000      953.000000          953.000000  953.000000   
mean    51.431270   64.279119       27.057712            1.581322   18.213012   
std     23.480632   16.550526       25.996077            8.409800   13.711223   
min      4.000000    9.000000        0.000000            0.000000    3.000000   
25%     32.000000   53.000000        6.000000            0.000000   10.000000   
50%     51.000000   66.000000       18.000000            0.000000   12.000000   
75%     70.000000   77.000000       43.000000            0.000000   24.000000   
max     97.000000   97.000000       97.000000           91.000000   97.000000   

       speechiness_%  
count     953.000000  
mean       10.131165  
std         9.912888  
min         2.000000  
25%         4.000000  
50%         6.000000  
75%        11.000000  
max        64.000000

Then we clean the data. To clean our data we first check for null values.

In [6]:
df.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

Then we drop the non zero values.In shazam charts and key have non null values hence dropped and hence cleaned our data.

In [7]:
df.dropna(inplace=True)

In [8]:
print(df["streams"].dtype)


object


In [9]:
df["streams"] = pd.to_numeric(df["streams"], errors="coerce")


In [10]:
pd.set_option("display.float_format", "{:.2f}".format)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   track_name            817 non-null    object 
 1   artist(s)_name        817 non-null    object 
 2   artist_count          817 non-null    int64  
 3   released_year         817 non-null    int64  
 4   released_month        817 non-null    int64  
 5   released_day          817 non-null    int64  
 6   in_spotify_playlists  817 non-null    int64  
 7   in_spotify_charts     817 non-null    int64  
 8   streams               816 non-null    float64
 9   in_apple_playlists    817 non-null    int64  
 10  in_apple_charts       817 non-null    int64  
 11  in_deezer_playlists   817 non-null    object 
 12  in_deezer_charts      817 non-null    int64  
 13  in_shazam_charts      817 non-null    object 
 14  bpm                   817 non-null    int64  
 15  key                   817 no

Most popular artists on Spotify by streams.

In [12]:
most_popular_artists = (df.groupby("artist(s)_name")["streams"].sum().sort_values(ascending=False))
print("Most popular artists:\n", most_popular_artists.head())


Most popular artists:
 artist(s)_name
Taylor Swift   11851151082.00
Ed Sheeran     11051252012.00
Bad Bunny       8582384095.00
Eminem          6183805596.00
The Weeknd      6038640754.00
Name: streams, dtype: float64


Taylor Swift is the most popular artist in Spotify with 1.18 billion streams followed by Ed Sheeran with 1.1 billion streams, then Bad Bunny with 858 million streams. Eminem follows with 618 million streams, then The Weeknd with 603 million streams. Since Taylor Swift has the most streams on Spotify, she is probably the most paid artist on Spotify because the allocation of royalties depends on the number of streams per artist.

Top artists that produced the most hits on Spotify.

In [13]:
number_of_hits_per_artist=(df["artist(s)_name"].value_counts().head())
print(number_of_hits_per_artist)

artist(s)_name
Taylor Swift      29
SZA               17
Bad Bunny         16
The Weeknd        15
Kendrick Lamar    12
Name: count, dtype: int64


Taylor Swift has a total of 34 hit songs on the Popular Spotify songs list followed by The Weeknd with 22  hit songs, then Bad Bunny and SZA with 19 hit songs,then Harry Styles with 17 songs. Hence Taylor Swift has the most hits on Spotify. A song released by Taylor Swift or SZA is likely to become a hit because the artists have most released hits and are also popular.

Most streamed songs on Spotify

In [14]:
top_songs = df.groupby("track_name")["streams"].sum().sort_values(ascending=False).head(5)
print(top_songs)


track_name
Shape of You                                    3562543890.00
Sunflower - Spider-Man: Into the Spider-Verse   2808096550.00
One Dance                                       2713922350.00
STAY (with Justin Bieber)                       2665343922.00
Believer                                        2594040133.00
Name: streams, dtype: float64


The top 5 most steamed songs on Spotify is Shape of You with 3.5 billion streams followed by Sunflower with 2.8 billion streams,One Dance with 2.71 billion streams and Stay with 2.6 billion streams. Shape of you by Ed Sheeran is the most streamed song on Spotify.

Average streams per year

In [15]:
df = df[df["released_year"] >= 2000]
avg_streams_per_year = (df.groupby("released_year")["streams"] .mean() .sort_index())
print(avg_streams_per_year)

released_year
2000   1224285700.33
2002   1446620470.50
2003   1584021370.50
2004    952664875.33
2005    180577478.00
2008   1240407950.00
2010   1048400819.17
2011    878452623.44
2012   1029740974.67
2013   1362225297.20
2014   1275126822.67
2015    910423256.33
2016   1135476212.53
2017   1497372434.68
2018   1349253397.33
2019    858923124.44
2020    784012453.13
2021    548942993.67
2022    279439530.51
2023    143932389.40
Name: streams, dtype: float64


The average streams per year was the highest between 2012 and 2018 with streams above 1 billion. This shows that during this period, massively popular songs were released.The average streams per year have also increased since 2000, showing that newer songs tend to get more streams, likely due to the growth of Spotify and the streaming culture. However, some older songs like Yellow	by Chris Molitor still dominate the top streams, creating spikes in certain years.

Visualizations

Bar chart showing most popular artists on Spotify by streams

In [20]:
artist_streams = (
    df.groupby("artist(s)_name")["streams"].sum()
      .sort_values(ascending=False)[:10])

plt.figure(figsize=(12,8))
plt.bar(artist_streams.index, artist_streams.values, color=("red"))
plt.title("Top 10 Artists by Total Streams")
plt.xlabel("Artist")
plt.ylabel("Total Streams(in billions)")
plt.show()

Artists like Taylor Swift, Ed Sheeran, The Weeknd appear multiple times to mean that popular artists consistently produce high-stream songs. A song featured by Taylor Swift and Ed Sheeran is likely to hit the chats because they are popular. Same to a son released by The Weeknd and Eminem or Harry Styles.

Trendline showing average streams per release year

In [17]:
avg_per_year = df.groupby("released_year")["streams"].mean()
avg_per_year.plot(kind="line", marker=" ")
plt.xlabel("Release year")
plt.ylabel("Average Streams")
plt.title("Average Streams by Release Year")
plt.show()


In [18]:
year_2003 = df[df["released_year"] == 2003]
print(year_2003.head())

         track_name artist(s)_name  artist_count  released_year  \
331            Numb    Linkin Park             1           2003   
630  Mr. Brightside    The Killers             1           2003   

     released_month  released_day  in_spotify_playlists  in_spotify_charts  \
331               3            24                 20111                  5   
630               9            23                 51979                 15   

          streams  in_apple_playlists  ...  bpm key   mode danceability_%  \
331 1361425037.00                  39  ...  110   A  Major             50   
630 1806617704.00                 306  ...  148  C#  Major             35   

     valence_% energy_% acousticness_%  instrumentalness_%  liveness_%  \
331         24       86              0                   0          64   
630         24       93              0                   0          10   

     speechiness_%  
331              4  
630              8  

[2 rows x 24 columns]


It is clear that songs like Numb and Mr.Brightside released in 2003 had the most streams in average over the years with both songs having more than a billion streams in 1 year.It is also clear that songs released in 2005 did not get as much streams hence a sharp drop. There is a huge stream growth in songs released from 2010 to 2020, showing most popular songs on Spotify were released during this time. 

Bar chat showing top 10 most streamed songs 

In [19]:
top_songs = df.groupby("track_name")["streams"].sum().sort_values(ascending=False)[:10]
plt.figure(figsize=(12,8))
plt.bar(top_songs.index, top_songs.values)
plt.xticks(ha="center", va="bottom",fontsize=9, rotation=90)  
plt.xlabel("Songs")
plt.ylabel("Total Streams(in billions)")
plt.title("Top 10 Most Streamed Songs")
plt.show()

Shape of you by Ed Sheeran is the most streamed song on Spotify with 3.5 billion streams followed by Sunflower with 2.8 billion streams,One Dance with 2.71 billion streams and Stay with 2.6 billion streams. 

Conclusion

In conclusion,the average streams per year tend to increase for newer release years, reflecting Spotify’s growth and the popularity of streaming in the 2010s and 2020s.Most popular artists also have the most streams meaning the streams are mostly influenced by the popularity of the artist.Popular artists also influence the number of streams. Songs featured with popular artists are likely to have more streams.